export const SET_BOARD_DIMENSIONS = 'SET_BOARD_DIMENSIONS';
export const SET_BOARD_DIMENSIONS_ERROR = 'SET_BOARD_DIMENSIONS_ERROR';
export const SET_BOARD_DIMENSIONS_SUCCESS = 'SET_BOARD_DIMENSIONS_SUCCESS';

export const SET_STREAK_SIZE = 'SET_STREAK_SIZE';
export const SET_STREAK_SIZE_ERROR = 'SET_STREAK_SIZE_ERROR';
export const SET_STREAK_SIZE_SUCCESS = 'SET_STREAK_SIZE_SUCCESS';

export const INVALIDATE_BOARD = 'INVALIDATE_BOARD';

export const RESET_BOARD = 'RESET_BOARD';
export const RESET_BOARD_ERROR = 'RESET_BOARD_ERROR';
export const RESET_BOARD_SUCCESS = 'RESET_BOARD_SUCCESS';

export const CHANGE_BOARD_VALUE = 'CHANGE_BOARD_VALUE';
export const CHANGE_BOARD_VALUE_ERROR = 'CHANGE_BOARD_VALUE_ERROR';
export const CHANGE_BOARD_VALUE_SUCCESS = 'CHANGE_BOARD_VALUE_SUCCESS';

export const SET_WINNER = 'SET_WINNER';